//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funlam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docentes
    {
        public int IdDocente { get; set; }
        public string NombreDocente { get; set; }
        public string ApellidoDocente { get; set; }
        public string Telefono { get; set; }
    }
}
